---
- name: Install rbenv
  become: true
  apt:
    name: rbenv
- name: Setup rbenv
  shell: >
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(rbenv init -)"' >> ~/.bashrc
