---
- name: Update /etc/ssh/sshd_config
  become: true
  copy:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
- name: Make /home/pi/.ssh directory
  file:
    path: /home/pi/.ssh
    state: directory
    owner: pi
    group: pi
    mode: "u=rwx,g=rx,o=rx"
- name: Update /home/pi/.ssh/authorized_keys
  copy:
    src: home/pi/.ssh/authorized_keys
    dest: /home/pi/.ssh/authorized_keys
    owner: pi
    group: pi
    mode: "u=rw,g=r,o=r"
- name: Reload sshd config
  become: true
  service:
    name: sshd
    state: reloaded
    enabled: true
